//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentLinkUp_MVC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearningMaterial()
        {
            this.Meetings = new HashSet<Meeting>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int materialID { get; set; }
        public int materialType { get; set; }
        public int username { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public Nullable<int> edition { get; set; }
        public decimal price { get; set; }
        public int condition { get; set; }
        public string moduleName { get; set; }
        public Nullable<bool> available { get; set; }
        public string Bookimage { get; set; }
        public bool enabled { get; set; }
    
        public virtual Condition Condition1 { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Module Module { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
