//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentLinkUp_MVC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int meetingID { get; set; }
        public string meetingLocation { get; set; }
        public System.DateTime meetingDate { get; set; }
        public System.TimeSpan meetingTime { get; set; }
        public bool success { get; set; }
        public int userID_buyer { get; set; }
        public int userID_seller { get; set; }
        public int materialID { get; set; }
    
        public virtual LearningMaterial LearningMaterial { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
