//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentLinkUp_MVC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int receiptNum { get; set; }
        public int meetingID { get; set; }
        public int itemName { get; set; }
        public decimal total { get; set; }
        public System.DateTime meetingDate { get; set; }
        public System.TimeSpan meetingTime { get; set; }
    
        public virtual LearningMaterial LearningMaterial { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
}
