//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentLinkUp_MVC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int reviewID { get; set; }
        public Nullable<int> userID_Seller { get; set; }
        public Nullable<int> userID_Buyer { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string review1 { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
